### PR TITLE
Update to 1.20.x

### PR DESCRIPTION
**Pull request by aarch-angel**
Updated code to 1.20.1, but it also works for 1.20.2. I haven't bumped the mod version number, since I don't know what you'd like to set that to.

Thanks for the fun mod!

### CODE REVIEW

**Comment by valoeghese** [comment]
Hol up, i'll make a new branch, then can you close this PR and open another one to that branch? thanks.
Alternatively change the target branch of this PR to the new branch if GitHub lets you, but I seem to recall that not being possible

**Comment by valoeghese** [comment]
New branch created: https://github.com/valoeghese/Dash/tree/1.20

**Comment by aarch-angel** [comment]
I've changed the base branch to the new 1.20 branch, seems like GitHub let me edit the PR!

**Review by valoeghese — APPROVED** [review]
Thanks for the contribution!

**Pull request merged**
